server:
  port: 8081
spring:
  datasource:
    password: Sh517jA
    url: jdbc:mysql://127.0.0.1:3306/jwt_security?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: SHISIA
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: create-drop
    database: mysql
  redis:
    host: localhost
    port: 6379
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
